### ISSUE TITLE
SQLException caused by RSA public key

### ISSUE THREAD

**Issue by dannyldj** [Euphillya/Skyllia#25]
```
[02:56:01 FATAL]: [fr.euphyllia.skyllia.api.database.sgbd.MariaDB] RSA public key is not available client side (option serverRsaPublicKeyFile not set)
java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
	at org.mariadb.jdbc.plugin.authentication.standard.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:221) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:264) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:194) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:69) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:95) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:26) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.database.sgbd.MariaDB.onLoad(MariaDB.java:41) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.database.DatabaseLoader.loadDatabase(DatabaseLoader.java:25) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.InterneAPI.setupSGBD(InterneAPI.java:129) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.Main.onEnable(Main.java:60) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-21]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-21]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-21]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-21]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:56:01 FATAL]: [fr.euphyllia.skyllia.Main] fr.euphyllia.skyllia.api.exceptions.DatabaseException: java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
fr.euphyllia.skyllia.api.exceptions.DatabaseException: java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
	at fr.euphyllia.skyllia.api.database.sgbd.MariaDB.onLoad(MariaDB.java:49) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.database.DatabaseLoader.loadDatabase(DatabaseLoader.java:25) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.InterneAPI.setupSGBD(InterneAPI.java:129) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.Main.onEnable(Main.java:60) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-21]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-21]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-21]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-21]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-21]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
	at org.mariadb.jdbc.plugin.authentication.standard.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:221) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:264) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:194) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:69) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:95) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at org.mariadb.jdbc.Driver.connect(Driver.java:26) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.api.database.sgbd.MariaDB.onLoad(MariaDB.java:41) ~[Skyllia-1.0-RC3.2-all.jar:?]
	... 15 more
```

The exception is thrown even though `useSSL = false`. Something to try?

**Comment by Euphillya** [comment]
Are you sure that your RSA key is correct?.

**Comment by Euphillya** [comment]
after I've never used an RSA key to connect.

**Comment by dannyldj** [comment]
I also want to connect with a username and password, but I'm getting an exception.

**Comment by dannyldj** [comment]
My fault. I installed MySQL and not MariaDB.
