### ISSUE TITLE
Exception on stop after first run server

### ISSUE THREAD

**Issue by dannyldj** [Euphillya/Skyllia#26]
```
[14:16:59 FATAL]: [fr.euphyllia.skyllia.api.database.execute.MariaDBExecute] [MARIADB] - Query :     INSERT IGNORE INTO `sky_folia`.`spiral`
    (id, region_x, region_z)
    VALUES(?, ?, ?);

fr.euphyllia.skyllia.api.exceptions.DatabaseException: Cannot get connection to the database
	at fr.euphyllia.skyllia.api.database.execute.MariaDBExecute.executeQuery(MariaDBExecute.java:45) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at fr.euphyllia.skyllia.database.query.MariaDBCreateTable.lambda$init$0(MariaDBCreateTable.java:145) ~[Skyllia-1.0-RC3.2-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:16:59 WARN]: Exception in thread "pool-16-thread-1" java.lang.RuntimeException: fr.euphyllia.skyllia.api.exceptions.DatabaseException: fr.euphyllia.skyllia.api.exceptions.DatabaseException: Cannot get connection to the database
[14:16:59 WARN]: 	at Skyllia-1.0-RC3.2-all.jar//fr.euphyllia.skyllia.database.query.MariaDBCreateTable.lambda$init$0(MariaDBCreateTable.java:147)
[14:16:59 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:16:59 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:16:59 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[14:16:59 WARN]: Caused by: fr.euphyllia.skyllia.api.exceptions.DatabaseException: fr.euphyllia.skyllia.api.exceptions.DatabaseException: Cannot get connection to the database
[14:16:59 WARN]: 	at Skyllia-1.0-RC3.2-all.jar//fr.euphyllia.skyllia.api.database.execute.MariaDBExecute.executeQuery(MariaDBExecute.java:59)
[14:16:59 WARN]: 	at Skyllia-1.0-RC3.2-all.jar//fr.euphyllia.skyllia.database.query.MariaDBCreateTable.lambda$init$0(MariaDBCreateTable.java:145)
[14:16:59 WARN]: 	... 3 more
[14:16:59 WARN]: Caused by: fr.euphyllia.skyllia.api.exceptions.DatabaseException: Cannot get connection to the database
[14:16:59 WARN]: 	at Skyllia-1.0-RC3.2-all.jar//fr.euphyllia.skyllia.api.database.execute.MariaDBExecute.executeQuery(MariaDBExecute.java:45)
[14:16:59 WARN]: 	... 4 more
```

**Comment by Euphillya** [comment]
You can ignore this bug, but I'll make sure it doesn't happen again.
