### ISSUE TITLE
Provides an option to disable the event of returning to the spawn of the world

### ISSUE THREAD

**Issue by 404forever1** [Euphillya/Skyllia#37]

**Comment by Euphillya** [comment]
that's to say ?

**Comment by Euphillya** [comment]
@404forever1 https://github.com/Euphillya/Skyllia/actions/runs/9078177436

**Comment by 404forever1** [comment]
[00:47:53 INFO]: [Skyllia] Enabling Skyllia v1.0-RC7-16
[00:47:53 INFO]: [fr.euphyllia.skyllia.Main] Plugin Start
[00:47:53 ERROR]: Error occurred while enabling Skyllia v1.0-RC7-16 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/RegistryAccess
        at fr.euphyllia.skyllia.api.InterneAPI.setVersionNMS(InterneAPI.java:152) ~[Skyllia-1.0-RC7-16-all.jar:?]
        at fr.euphyllia.skyllia.api.InterneAPI.<init>(InterneAPI.java:47) ~[Skyllia-1.0-RC7-16-all.jar:?]
        at fr.euphyllia.skyllia.Main.onEnable(Main.java:47) ~[Skyllia-1.0-RC7-16-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 15 more
[00:47:53 INFO]: [Skyllia] Disabling Skyllia v1.0-RC7-16
[00:47:53 INFO]: [fr.euphyllia.skyllia.Main] Plugin Off
[00:47:53 ERROR]: Error occurred while disabling Skyllia v1.0-RC7-16
java.lang.NullPointerException: Cannot invoke "fr.euphyllia.skyllia.dependency.energie.Energie.getNativeScheduler()" because "fr.euphyllia.skyllia.api.SkylliaAPI.energie" is null
        at fr.euphyllia.skyllia.api.SkylliaAPI.getNativeScheduler(SkylliaAPI.java:47) ~[Skyllia-1.0-RC7-16-all.jar:?]
        at fr.euphyllia.skyllia.Main.onDisable(Main.java:90) ~[Skyllia-1.0-RC7-16-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Euphillya** [comment]
@404forever1 fixed https://github.com/Euphillya/Skyllia/pull/36/commits/aef3026bbb2581e7bb000f9483b99161e506d4ee

download : https://github.com/Euphillya/Skyllia/actions/runs/9084673012

**Comment by 404forever1** [comment]
console stop here , icant join server
[11:14:22 INFO]: [Skyllia] Loading server plugin Skyllia v1.0-RC7-18
[11:14:22 INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:14:22 INFO]: [WorldEdit] Enabling WorldEdit v7.3.0-SNAPSHOT+8ddbd3a
[11:14:22 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[11:14:22 INFO]: WEPIF: Using the Bukkit Permissions API.
[11:14:23 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter as the Bukkit adapter
[11:14:24 INFO]: Preparing level "world"
[11:14:24 INFO]: Preparing start region for dimension minecraft:overworld
[11:14:24 INFO]: Time elapsed: 13 ms
[11:14:24 INFO]: Preparing start region for dimension minecraft:the_nether
[11:14:25 INFO]: Time elapsed: 7 ms
[11:14:25 INFO]: Preparing start region for dimension minecraft:the_end
[11:14:25 INFO]: Time elapsed: 5 ms
[11:14:25 INFO]: [Skyllia] Enabling Skyllia v1.0-RC7-18
[11:14:25 INFO]: [fr.euphyllia.skyllia.Main] Plugin Start
[11:14:25 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[11:14:25 INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection org.mariadb.jdbc.Connection@69c46b13
[11:14:25 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[11:14:25 INFO]: [fr.euphyllia.skyllia.dependency.sgbd.MariaDB] MariaDB pool initialized (5)

**Comment by 404forever1** [comment]
load very slow ，wait 1 min，34:17-》35：17
[11:34:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[11:34:17 INFO]: [fr.euphyllia.skyllia.dependency.sgbd.MariaDB] MariaDB pool initialized (5)
[11:35:17 WARN]: [fr.euphyllia.skyllia.Main] Disable nether in server.properties to disable nether portals!
[11:35:17 WARN]: [fr.euphyllia.skyllia.Main] Disable end in bukkit.yml to disable end portals!
[11:35:18 INFO]: Done (66.782s)! For help, type "help"
[11:35:18 ERROR]: No key layers in MapLike[{}]
[11:35:18 INFO]: Initialising world 'world' before it can be ticked...
[11:35:18 INFO]: Initialising world 'world_nether' before it can be ticked...

**Comment by Euphillya** [comment]
> load very slow ，wait 1 min，34:17-》35：17 [11:34:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed. [11:34:17 INFO]: [fr.euphyllia.skyllia.dependency.sgbd.MariaDB] MariaDB pool initialized (5) [11:35:17 WARN]: [fr.euphyllia.skyllia.Main] Disable nether in server.properties to disable nether portals! [11:35:17 WARN]: [fr.euphyllia.skyllia.Main] Disable end in bukkit.yml to disable end portals! [11:35:18 INFO]: Done (66.782s)! For help, type "help" [11:35:18 ERROR]: No key layers in MapLike[{}] [11:35:18 INFO]: Initialising world 'world' before it can be ticked... [11:35:18 INFO]: Initialising world 'world_nether' before it can be ticked...

Send me a report spark

**Comment by Euphillya** [comment]
Cannot be reproduced, and no response for 10 days. If the problem persists, please reopen a request.
